apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${JOB_NAME}
  labels:
    app: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      build_number: ${BUILD_NUMBER}
      app: ${JOB_NAME}
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: ${JOB_NAME}-container
        image: ${REGISTRY}/${JOB_NAME}:v$BUILD_NUMBER"
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: my-service
spec:
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
      nodePort: 30007
  type: NodePort
